# Generated by Django 2.0.2 on 2018-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ISO', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
    ]
