# Generated by Django 2.0.2 on 2018-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikaquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='ISO',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Name',
            new_name='name',
        ),
    ]
