# Generated by Django 2.0.2 on 2018-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afrikaquiz', '0002_auto_20180301_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrikaquiz.Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrikaquiz.Person')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='leaders',
            field=models.ManyToManyField(through='afrikaquiz.Leadership', to='afrikaquiz.Person'),
        ),
    ]
