# Generated by Django 2.0.2 on 2018-03-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikaquiz', '0003_auto_20180301_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='leadership',
            name='title',
            field=models.TextField(default='president', max_length=200),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='end',
            field=models.DateField(blank=True),
        ),
    ]
