# Generated by Django 2.0.2 on 2018-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikaquiz', '0005_auto_20180301_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(default='president', max_length=200),
        ),
    ]
