INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (2,'José Eduardo dos Santos');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (17,'Pierre Nkurunziza');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (19,'Yayi Boni');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (20,'Blaise Compaoré');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (35,'Ian Khama');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (36,'Michel Djotodia');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (43,'Alassane Ouattara');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (44,'Paul Biya');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (46,'Ikililou Dhoinine');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (47,'Jorge Carlos Fonseca');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (51,'Joseph Kabila');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (54,'Ismaïl Omar Guelleh');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (59,'Abdelaziz Bouteflika');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (61,'Adly Mansour');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (62,'Isaias Afewerki');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (65,'Toomas Hendrik Ilves');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (70,'Ali Bongo Ondimba');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (73,'John Dramani Mahama');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (74,'Alpha Condé');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (75,'Yahya Jammeh');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (76,'Manuel Serifo Nhamadjo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (77,'Teodoro Obiang Nguema Mbasogo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (102,'Uhuru Kenyatta');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (111,'Ellen Johnson Sirleaf');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (112,'Nouri Abusahmain');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (118,'Letsie III');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (122,'Muhammad VI');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (125,'Andry Rajoelina');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (130,'Ibrahim Boubacar Keïta');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (135,'Armando Guebuza');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (136,'Mohamed Ould Abdel Aziz');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (137,'Kailash Purryag');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (138,'Joyce Banda');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (140,'Hifikepunye Pohamba');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (141,'Mahamadou Issoufou');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (144,'Goodluck Jonathan');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (164,'Denis Sassou Nguesso');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (168,'Paul Kagame');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (170,'Omar al-Bashir');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (171,'Macky Sall');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (176,'Ernest Bai Koroma');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (180,'Hassan Sheikh Mohamud');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (182,'Salva Kiir Mayardit');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (183,'Manuel Pinto da Costa');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (188,'Mswati III');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (189,'James Michel');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (190,'Idriss Déby');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (191,'Faure Gnassingbé');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (192,'Bhumibol Adulyadej');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (197,'Moncef Marzouki');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (201,'Jakaya Kikwete');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (202,'Yoweri Museveni');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (215,'Jacob Zuma');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (216,'Michael Sata');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (217,'Robert Mugabe');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (301,'Canaan Banana');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (302,'Nelson Mandela');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (303,'Thabo Mbeki');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (304,'Kgalema Motlanthe');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (305,'Kenneth Kaunda');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (306,'Frederick Chiluba');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (307,'Levy Mwanawasa');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (308,'Rupiah Banda');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (310,'Frederick Mutesa');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (311,'Milton Obote');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (312,'Idi Amin');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (314,'Yusuf Lule');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (315,'Godfrey Binaisa');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (316,'Paulo Muwanga');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (318,'Bazilio Olara-Okello');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (319,'Tito Okello');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (320,'Julius Nyerere');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (321,'Ali Hassan Mwinyi');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (322,'Benjamin Mkapa');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (401,'António Agostinho Neto');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (402,'Michel  Micombero');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (403,'Jean-Baptiste  Bagaza');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (404,'Jean-Baptiste  Bagaza');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (405,'Pierre Buyoya');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (406,'Pierre Buyoya');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (407,'Melchior Ndadaye');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (408,'Francois Ngeze');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (409,'Sylvie Kinigi');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (410,'Cyprien Ntaryamira');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (411,'Sylvestre Ntibantunganya');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (412,'Pierre Buyoya');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (413,'Domitien Ndayizeye');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (414,'Hubert Maga');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (417,'Christophe Soglo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (418,'Sourou-Migan Apithy');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (419,'Justin Ahomadegbe');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (420,'Tahirou Congacou');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (422,'Jean-Baptiste Hacheme');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (423,'Maurice Kouandété');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (424,'Alphonse Alley');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (425,'Émile Zinsou');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (427,'Paul-Émile de Souza');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (428,'Hubert Maga');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (430,'Mathieu Kérékou');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (433,'Nicéphore Soglo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (440,'Maurice Yaméogo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (441,'Sangoulé Lamizana');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (442,'Saye Zerbo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (443,'Jean-Baptiste Ouédraogo');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (444,'Thomas Sankara');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (445,'Blaise Compaoré');
INSERT INTO `afrikaquiz_person` (`id`,`name`) VALUES (446,'Cyril  Ramaphosa');
