INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('AGO','Angola');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('BDI','Burundi');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('BEN','Benin');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('BFA','Burkina Faso');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('BWA','Botswana');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('CAF','Central African Republic');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('CIV','Côte d\'Ivoire');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('CMR','Cameroon');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('COD','Democratic Republic of the Congo');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('COG','Republic of Congo');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('COM','Comoros');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('CPV','Cape Verde');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('DJI','Djibouti');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('DZA','Algeria');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ERI','Eritrea');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ETH','Ethiopia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GAB','Gabon');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GBR','United Kingdom');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GHA','Ghana');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GIN','Guinea');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GMB','Gambia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GNB','Guinea-Bissau');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('GNQ','Equatorial Guinea');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ITA','Italy');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('KEN','Kenya');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('LBR','Liberia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('LBY','Libya');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('LSO','Lesotho');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MAR','Morocco');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MDG','Madagascar');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MLI','Mali');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MOZ','Mozambique');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MRT','Mauritania');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MUS','Mauritius');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('MWI','Malawi');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('NAM','Namibia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('NER','Niger');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('NGA','Nigeria');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('PRT','Portugal');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('RWA','Rwanda');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SDN','Sudan');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SEN','Senegal');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SLE','Sierra Leone');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SOM','Somalia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SSD','South Sudan');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('STP','São Tomé and Príncipe');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SWZ','Swaziland');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('SYC','Seychelles');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('TCD','Chad');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('TGO','Togo');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('TUN','Tunisia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('TZA','Tanzania');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('UGA','Uganda');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('USA','United States');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ZMB','Zambia');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ZWE','Zimbabwe');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('ZAF','South Africa');
INSERT INTO `afrikaquiz_country` (`iso`,`name`) VALUES ('EGY','Egypt');
