# Generated by Django 2.0.2 on 2018-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('statistikk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataset',
            new_name='Datasett',
        ),
    ]
