# Generated by Django 2.0.2 on 2018-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistikk', '0002_auto_20180313_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasett',
            name='enhet',
            field=models.CharField(default='minutter', max_length=200),
        ),
    ]
