# Generated by Django 2.0.2 on 2018-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistikk', '0003_datasett_enhet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sammenligning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasett', models.ManyToManyField(to='statistikk.Datasett')),
            ],
        ),
    ]
