# Generated by Django 2.0.2 on 2018-03-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistikk', '0004_sammenligning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dataset',
            new_name='datasett',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='value',
            new_name='verdi',
        ),
    ]
